sudo: required

services:
- docker

env:
  global:
    - REPO=michaelvl/grafanalib
    - GITCOMMIT=${TRAVIS_COMMIT::7}

jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t $REPO:$GITCOMMIT .
      - docker images
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $REPO:$GITCOMMIT

