version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    environment:
      REPO=michaelvl/grafanalib
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup environment variables
          command: |
            echo 'GITCOMMIT=${CIRCLE_SHA1::7}' >> $BASH_ENV
	    NOW=$(date +%Y%m%d-%H%M)
	    FULLNAME="$REPO:git-$NOW-$GITCOMMIT"
	    echo "FULLNAME=$FULLNAME" >> $BASH_ENV
            echo "Branch $CIRCLE_BRANCH"
            echo "Using full name $FULLNAME"
      - run:
          name: Build container image
          command: |
            docker build -t $FULLNAME .
      - run:
          name: Push container image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $FULLNAME
